# MLops

In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])

### Opérations des vecteurs : 

In [24]:
su=a+b
so=b-a
di=a==b
print(su)
print(so)
print(di)

[5 7 9]
[3 3 3]
[False False False]


In [26]:
a=np.append(a,10)
b=np.append(b,10)

In [27]:
np.concatenate((a,b))

array([ 1,  2,  3, 10,  4,  5,  6, 10])